version: '3'
services:
  database:
    container_name: neotech-database
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=neotech
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassw
    restart: always
    ports:
      - "3306:3306"


  app:
    build: .
    container_name: neotech-demo-app
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassw
      - DB_SCHEME=neotech
      - CONNECTION_TIMEOUT=5000
      - TIMER_PERIOD=1000